UERANSIM v3.2.6
[2023-09-18 09:41:13.721] [sctp] [info] Trying to establish SCTP connection... (192.168.0.111:38412)
[2023-09-18 09:41:14.180] [sctp] [info] SCTP connection established (192.168.0.111:38412)
[2023-09-18 09:41:14.181] [sctp] [debug] SCTP association setup ascId[37]
[2023-09-18 09:41:14.181] [ngap] [debug] Sending NG Setup Request
[2023-09-18 09:41:14.312] [ngap] [debug] NG Setup Response received
[2023-09-18 09:41:14.312] [ngap] [info] NG Setup procedure is successful
[2023-09-18 09:41:19.273] [rrc] [debug] UE[1] new signal detected
[2023-09-18 09:41:19.284] [rrc] [info] RRC Setup for UE[1]
[2023-09-18 09:41:19.304] [ngap] [debug] Initial NAS message received from UE[1]
[2023-09-18 09:41:19.840] [ngap] [debug] Initial Context Setup Request received
[2023-09-18 09:41:20.347] [ngap] [info] PDU session resource(s) setup for UE[1] count[1]
[2023-09-18 09:41:20.462] [ngap] [info] PDU session resource(s) setup for UE[1] count[1]
terminate called after throwing an instance of 'LibError'
  what():  sendto failed:  Network is unreachable
